name: 'CI'

env:
  NODE_ENV: production

on: ['push']

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: npm
      - name: Install
        run: npm install
      - name: Lint TS
        run: cd node_modules && ls -la && cd bin && ls -la
      # - name: Lint CSS
      #   run: ls && pwd && npm run lint:css
